# Generated by Django 5.2.17 on 2026-09-17 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def mark_existing_emails_verified(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    user_model.objects.filter(email_verified_at__isnull=True).update(email_verified_at=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_emails_verified, migrations.RunPython.noop),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='accounts_us_blocker_c24ecb_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block')],
            },
        ),
    ]
