# Generated by Django 5.2.17 on 2026-09-17 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product_suspended', 'Anuncio suspenso'), ('product_reactivated', 'Anuncio reativado'), ('product_deleted', 'Anuncio eliminado'), ('image_approved', 'Imagem aprovada'), ('image_rejected', 'Imagem rejeitada'), ('user_deactivated', 'Conta desativada'), ('user_verified', 'Vendedor verificado'), ('report_resolved', 'Denuncia resolvida'), ('report_dismissed', 'Denuncia ignorada')], max_length=40)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.PositiveBigIntegerField()),
                ('target_label', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='reports_mod_action_6c8f57_idx')],
            },
        ),
    ]
