# Generated by Django 5.2.17 on 2026-09-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_moderationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('account', 'Conta e acesso'), ('listing', 'Anuncio'), ('safety', 'Seguranca ou fraude'), ('privacy', 'Privacidade e dados'), ('technical', 'Problema tecnico'), ('other', 'Outro assunto')], max_length=24)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em tratamento'), ('resolved', 'Resolvido')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_sup_status_dbb359_idx')],
            },
        ),
    ]
