# Generated by Django 5.2.17 on 2026-09-17 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('system', 'Sistema'), ('new_message', 'Nova mensagem'), ('product_reserved', 'Produto reservado'), ('product_sold', 'Produto vendido')], default='system', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at', 'created_at'], name='notificatio_user_id_478247_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['kind', 'created_at'], name='notificatio_kind_e256fc_idx'),
        ),
    ]
