# Generated by Django 5.2.17 on 2026-09-13 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('negotiable', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('new', 'Novo'), ('like_new', 'Como novo'), ('good', 'Bom estado'), ('used', 'Usado'), ('parts', 'Para pecas')], max_length=24)),
                ('province', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_review', 'Em analise'), ('active', 'Ativo'), ('reserved', 'Reservado'), ('sold', 'Vendido'), ('suspended', 'Suspenso'), ('deleted', 'Eliminado')], default='active', max_length=24)),
                ('featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-featured', '-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('review_required', 'Revisao necessaria'), ('rejected', 'Rejeitada')], default='pending', max_length=24)),
                ('moderation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'published_at'], name='products_pr_status_8124bb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'status'], name='products_pr_feature_20d464_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['city', 'status'], name='products_pr_city_11d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='products_pr_categor_75eeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'position'], name='products_pr_product_78e37c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['moderation_status'], name='products_pr_moderat_d0c8ed_idx'),
        ),
    ]
