# Generated by Django 5.2.17 on 2026-09-13 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('nuit', models.CharField(blank=True, max_length=40)),
                ('document_type', models.CharField(choices=[('bi', 'BI'), ('passport', 'Passaporte'), ('dire', 'DIRE'), ('other', 'Outro')], max_length=24)),
                ('document_number', models.CharField(max_length=80)),
                ('document_front', models.FileField(blank=True, null=True, upload_to='verification/private/')),
                ('document_back', models.FileField(blank=True, null=True, upload_to='verification/private/')),
                ('selfie', models.FileField(blank=True, null=True, upload_to='verification/private/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='verificatio_status_b771d1_idx')],
            },
        ),
    ]
