# Generated by Django 5.2.17 on 2026-09-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['is_active', 'sort_order'], name='categories__is_acti_e242f2_idx')],
            },
        ),
    ]
